# Generated by Django 2.1.2 on 2018-11-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kijisearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camps',
            name='camp_video_link',
        ),
        migrations.RemoveField(
            model_name='camps',
            name='register',
        ),
    ]
